apiVersion: apps/v1
kind: Deployment
metadata:
  name: aldotr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aldotr
  template:
    metadata:
      labels:
        app: aldotr
    spec:
      containers:
      - image: okteto.dev/aldotr:latest
        name: aldotr
        envFrom:
        - configMapRef:
            name: aldotr-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: aldotr
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "aldotr"
    port: 8080
  selector:
    app: aldotr
