apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-aldotr
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  phones-aldotr
  template:
    metadata:
      labels:
        app:  phones-aldotr
    spec:
      containers:
      - image: okteto.dev/phones-aldotr:latest
        name:  phones-aldotr
        envFrom:
        - configMapRef:
            name: aldotr-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name:  phones-aldotr
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "phones-aldotr"
    port: 8080
  selector:
    app:  phones-aldotr
