apiVersion: v1
kind: ConfigMap
metadata:
  name: aldotr-config
  labels:
    app: postgres
data:
  PROD_SECRET_KEY: secret
  PROD_DATABASE: 
  PROD_USER: 
  PROD_PASSWORD: 
  PROD_HOST: 
  PROD_PORT: "5432"
