# Generated by Django 3.1.3 on 2023-03-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celulares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celular',
            old_name='tamaño',
            new_name='tamano',
        ),
    ]
